export enum ApiErrorCode {
	INTERNAL_SERVER_ERROR,
	NICKNAME_ALREADY_IN_USE,
	EMAIL_ALREADY_IN_USE,
	EMAIL_AND_NICKNAME_ALREADY_IN_USE,
	EMAIL_OR_PASSWORD_NOT_VALID,
	URL_NOT_FOUND,
	VALIDATION_ERROR,
	NOT_AUTHORIZED,
	PLAYER_NOT_FOUND
}
